version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - ~/.npm 
            - ~/.cache
            
          key:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test